# config/config.yaml

notification:
  mode: "webhook"
  
  webhook:
    # url: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=56c79598-1731-4892-949b-c8becbf6b93d"
    url: "https://open.feishu.cn/open-apis/bot/v2/hook/d6e6dbec-3341-484c-a4d1-2b217bda814a" 
    
    # 需要 @ 的手机号 (可选，留空则不艾特)
    mention_list: [] 
  
  gold_webhook:
    # url: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=8d9d826a-05f3-4d3d-926b-45bcf581ba9c"
    url: "https://open.feishu.cn/open-apis/bot/v2/hook/32969fb4-87d7-4297-8124-dec34193e8de" 

schedules:
  times: ["12:00", "14:30", "16:00"]

# 黄金监控频率 (分钟)
gold_monitor_interval: 5

# 顶部大盘指数 (展示在卡片顶部)
indices:
  - name: "上证指数"
    symbol_ref: "sh000001"
    flag: "🇨🇳"

  - name: "中证A500"
    symbol_ref: "sh000510"
    flag: "🇨🇳"

  - name: "纳斯达克100"
    symbol_ref: "usNDX"
    flag: "🇺🇸"

# 持仓列表 (仅供日报使用)
holdings:
  - name: "南方中证A500ETF"
    symbol_ref: "sz159352"  

  - name: "天弘恒生科技"
    symbol_ref: "sh520920"
  
  - name: "黄金ETF"
    symbol_ref: "sh518880"  

  - name: "南方红利低波50ETF"
    symbol_ref: "sh515450" 

  - name: "南方有色金属ETF"
    symbol_ref: "sh512400"      

  - name: "鹏华粮食ETF"
    symbol_ref: "sz159698"      
  
  - name: "华夏机器人ETF"
    symbol_ref: "sh562500"      # 南方机器人ETF华夏

  - name: "南方电池ETF"
    symbol_ref: "sz159147"     

